# Generated by Django 5.1.3 on 2024-12-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_order_product_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
